import { OpaqueToken } from '@angular/core';

export const LANG_EN_NAME = 'en'; 

export const LANG_EN_TRANS = { 
    'menu.home' : 'Home',
    'menu.services': 'Services',
    'menu.jobs': 'Jobs',
    'menu.contact': 'Contact',

    'contact.heading1' : 'Contact',
    'contact.heading1Text' : 'You can contact us by :',
    'contact.email' : 'E-mail :',
    'contact.phone' : 'Phone : ',

    'home.welcome': 'Welcome at',
    'home.moreInfo':  'To find out more about us, chose a topic below',
    'home.becomeCustomer': 'Become a client',
    'home.services': 'Services',
    'home.jobs': 'Jobs',
    'home.contact': 'Contact',
    'home.products': 'Products',

    'customer.heading1': 'Become a client?',
    'customer.heading1Text1': 'Our service is focused on delivering quality at the defined deadlines',
    'customer.heading1Text2': 'For us, it is very important that your investment in custom software pays off in the future.',
    'customer.heading1Text3': 'We understand that for most of the companies, IT is a very high cost.',
    'customer.heading1Text4': 'But imagine that your processess are more streamlined?',
    'customer.heading1Text5': 'Then it means a profit for you, because you can spent more time for the core tasks of your enterprise.',
    'customer.heading2': 'Why chose our services?',
    'customer.heading2Text1': 'There are already a lot of players on the market.',
    'customer.heading2Text2': 'But our company can be proud on the knowledge and experience we can offer.',
    'customer.heading2Text3': 'For you, it is important that the required services remain within budget,',
    'customer.heading2Text4': 'and off course, the delivered product must last for a while.',
    'customer.heading2Text5': 'With all our developments, we keep this factors in mind',

    'jobs.heading1': 'Jobs',
    'jobs.heading1Text1': 'We are always looking for IT-profiles : .NET, java, web, ASP.NET, Android, IoS, architects, ...',
    'jobs.heading1Text2': 'You can always sent your resume to :',

    "services.heading1": "Our services?",
    "services.heading1Text1": "Our services are focused on quality and cover the requirements for business that need support in their IT-department.",
    "services.heading1Text2" : "To accomplish this, we can rely on years of experience in different domains and business sectors",
    "services.heading2": "Software on demand",
    "services.heading2Text1": "One of our core services is to create custom software for your business that fits your needs.",
    "services.heading2Text2": "This can go from giving support to an existing team, or to manage complete projects ourself",
    "services.heading3": "You need a specialist?",
    "services.heading3Text1": "Maybe your business already has an IT-department, but you are on a very close deadline and the delivery is in danger?",
    "services.heading3Text2": "Or your team has not the inhouse knowledge needed?",
    "services.heading3Text3": "Don't worry, we will solve this for you",
    "services.heading3Text4": "We will send you a specialist that can manage the problems or needs",
    "services.heading4": "Knowledge domains",
    "services.heading4Text1": "Our main developments are based on Microsoft technologies.",
    "services.heading4Text2": "We work mainly within the .NET environment",
    "services.presentationText": "To know more about us, download the presentation",

    "products.heading1" : "Products",
    "products.archie" : "Archie",
    "products.archieContent": "Archie is a software package that allows companies and organisations to master their data",
    "products.octane" : "Octane",
    "products.octaneContent": "Octane is a .NET library that allows developers to fast create applications using standard patterns and tools",
    "products.discoverArchie" : "Discover Archie",
    "products.discoverOctane" : "Discover Octane",

    "archie.pageTitle" : "Archie",
    "archie.titleContent" : "Archie is an application for administration and management of small and medium sized companies",

    "octane.pageTitle" : "Octane",
    "octane.introduction" : "Octane is a .NET library that provides base functionalities to build applications",
    "octane.data" : "Data",
    "octane.data.content" : "The data package contains base functionalities for data-access.",
    "octane.di" : "Dependency injection",
    "octane.localization" : "Localization",
    "octane.mvvm" : "Model-View-Viewmodel",
    "octane.service" : "WCF service",
    "octane.serviceAgent" : "Service agents",
    "octane.specification" : "Specification pattern",
    "octane.test" : "Unit testing",
    "octane.validation" : "Validation",
    "octane.wpf" : "WPF"
}